### ISSUE TITLE
Half OT: needing own logo

### ISSUE THREAD

**Issue by theuserbl** [shashlik/shashlik#29]
The current shashlik-logo or maskot is the one of TwitterBot:
http://iconsmash.com/Icon/FreeIcon/27643/twitterbot
http://animalnewyork.com/2015/10-best-twitterbots-also-net-art/
http://technoflix.com/how-to-write-a-twitter-bot/
http://www.twitze.de/

Only the "t" was changed to "s".

I think shashlik needing an own unique Logo and maskot.

**Comment by a-andreyev** [comment]
I guess we should create something like this:
![ScreenShot](https://dl.dropboxusercontent.com/u/39622126/Images/shashlik.svg)
Feel free to use, I've made it this inkscape, openclipart, creative commons, etc

**Comment by leinir** [comment]
Thanks for noting that one, Krzysztof, there's some design things going on at the moment in the KDE visual design group, who have graciously offered to help us with this stuff, and the icon is a high priority, because yes, that is obviously not a good thing :)

Alexey, thanks for that one - it might not work so well at small sizes, but i like the concept very much - in fact, i was looking for something like that (shortly, but still) when i was putting together the presentation for Akademy this weekend. Let's see what the VDG comes up with, they're pretty good at this stuff :D

**Comment by star-buck** [comment]
@ Alexey : Can you provide a png, so we can change it for now?

**Comment by luebking** [comment]
On Dienstag, 28. Juli 2015 02:33:33 CEST, Alexey Andreyev wrote:
> I guess we should create something like this:
> ![ScreenShot](https://dl.dropboxusercontent.com/u/39622126/Images/shashlik.svg)
> Feel free to use, I've made it this inkscape, openclipart, 
> creative commons, etc

Nice. Considered to make the shashlik bar
a) bigger
b) "/" rather than "\" (left to right culture - you're pointing down, not 
up ;-)

**Comment by a-andreyev** [comment]
I've updated original svg at my dropbox according to your messages.
Feel free to download it and edit as you want too.
And you easily can save png from svg any size you want (with imagemagick or via some online services), what image size you want?

**Comment by theuserbl** [comment]
Nice picture.
The pengin stands for Linux. Then there is the shashlik-symbol integrated.
But I miss something about Android.

As SVG-file:
![shashlik2 svg](http://imgh.us/shashlik2.svg)

As PNG-file:
![shashlik2 png](https://cloud.githubusercontent.com/assets/8337032/8934985/abbfff9c-354a-11e5-90f3-b3c7b48c923b.png)

Greatings
theuserbl

**Comment by a-andreyev** [comment]
3rd chunk close to penguin beak in my pic contains android head actually :)

**Comment by leinir** [comment]
Thank you all very much for the help! i've fiddled a little with the image and put it up on the page (the text didn't quite fit at smaller scales, and the old contents of the shashlik skewer were still there, so i snipped that out a bit). Comments very welcome, obviously, and thank you all again for the help! :) Not closing just yet, in case any of you have further comments :)

**Comment by star-buck** [comment]
looks nice :)

**Comment by star-buck** [comment]
in use for now
